name: seoul
channels:
  - defaults
dependencies:
  - ca-certificates=2022.07.19
  - certifi=2022.6.15
  - openssl=1.1.1q
  - pip=22.1.2
  - python=3.8.5
  - setuptools=63.4.1
  - sqlite=3.39.2
  - wheel=0.37.1
  - pip:
    - --find-links https://download.pytorch.org/whl/torch_stable.html
    - albumentations==1.2.1
    - colorama==0.4.5
    - contourpy==1.0.5
    - cycler==0.11.0
    - fonttools==4.37.2
    - imageio==2.21.3
    - joblib==1.2.0
    - kiwisolver==1.4.4
    - matplotlib==3.6.0
    - networkx==2.8.6
    - numpy==1.23.3
    - opencv-python==4.6.0.66
    - opencv-python-headless==4.6.0.66
    - packaging==21.3
    - pandas==1.4.4
    - pillow==9.2.0
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - pytz==2022.2.1
    - pywavelets==1.4.1
    - pyyaml==6.0
    - qudida==0.0.4
    - scikit-image==0.19.3
    - scikit-learn==1.1.2
    - scipy==1.9.1
    - seaborn==0.12.0
    - six==1.16.0
    - threadpoolctl==3.1.0
    - tifffile==2022.8.12
    - timm==0.6.7
    - torch==1.10.1+cu113
    - torchaudio==0.10.1+cu113
    - torchinfo==1.7.0
    - torchvision==0.11.2+cu113
    - tqdm==4.64.1
    - typing-extensions==4.3.0
